"""
app/services/auto_resolver.py

Automatically resolves expired crypto prediction events.

Runs every 60 seconds. For each open crypto event past its closes_at:
1. Fetches the current price from CoinGecko
2. Parses the event title to extract the coin + threshold/range
3. Determines the winning scenario (Yes or No)
4. Runs the full resolution logic (payouts, streaks, snapshots)

Supported event types (generated by event_generator.py):
  - "Will BTC be above $70,000 in 1 hour?"   → above/below threshold
  - "Will ETH stay between $2,100–$2,196...?" → price range check
"""

from __future__ import annotations

import asyncio
import logging
import re
from datetime import datetime

import httpx
from sqlalchemy.orm import Session, joinedload

from app.db import SessionLocal
from app.models.event import Event
from app.models.scenario import Scenario
from app.models.prediction import Prediction
from app.models.account import Account
from app.models.transaction import Transaction
from app.models.user import User
from app.models.probability_history import ScenarioProbabilityHistory

logger = logging.getLogger(__name__)

COINGECKO_URL = "https://api.coingecko.com/api/v3/simple/price"

COIN_KEYWORDS = {
    "BTC": "bitcoin",
    "ETH": "ethereum",
    "SOL": "solana",
    "BNB": "binancecoin",
}

CURRENCY = "usd"
CHECK_INTERVAL_SECONDS = 60


# ── Price fetching ────────────────────────────────────────────────────────────

async def fetch_current_prices() -> dict[str, float]:
    """Fetch live prices for all tracked coins."""
    params = {"ids": ",".join(COIN_KEYWORDS.values()), "vs_currencies": CURRENCY}
    async with httpx.AsyncClient(timeout=10) as client:
        response = await client.get(COINGECKO_URL, params=params)
        response.raise_for_status()
        data = response.json()

    # Invert to symbol → price
    id_to_symbol = {v: k for k, v in COIN_KEYWORDS.items()}
    return {
        id_to_symbol[coin_id]: float(data[coin_id][CURRENCY])
        for coin_id in COIN_KEYWORDS.values()
        if coin_id in data and CURRENCY in data[coin_id]
    }


# ── Event parsing ─────────────────────────────────────────────────────────────

def _detect_coin(title: str) -> str | None:
    """Detect which coin this event is about from the title."""
    t = title.upper()
    for symbol in COIN_KEYWORDS:
        if symbol in t:
            return symbol
    return None


def _parse_above_event(title: str) -> float | None:
    """
    Parse threshold from: "Will BTC be above $70,000 in 1 hour?"
    Returns the threshold price or None if can't parse.
    """
    match = re.search(r"above\s+\$([0-9,]+(?:\.[0-9]+)?)", title, re.IGNORECASE)
    if match:
        return float(match.group(1).replace(",", ""))
    return None


def _parse_range_event(title: str) -> tuple[float, float] | None:
    """
    Parse range from: "Will BTC stay between $68,820–$71,628 in 1 hour?"
    Returns (lower, upper) or None if can't parse.
    """
    match = re.search(
        r"between\s+\$([0-9,]+(?:\.[0-9]+)?)[–\-–]?\$?([0-9,]+(?:\.[0-9]+)?)",
        title, re.IGNORECASE
    )
    if match:
        lower = float(match.group(1).replace(",", ""))
        upper = float(match.group(2).replace(",", ""))
        return lower, upper
    return None


def _determine_winner(event: Event, current_price: float) -> tuple[int | None, str]:
    """
    Determine winning scenario ID and resolution note.
    Returns (winning_scenario_id, resolution_note) or (None, reason) if undetermined.
    """
    title = event.title
    scenarios = sorted(event.scenarios, key=lambda s: s.sort_order)

    if not scenarios:
        return None, "No scenarios found"

    # Detect event type
    range_result = _parse_range_event(title)
    above_threshold = _parse_above_event(title)

    if range_result:
        lower, upper = range_result
        in_range = lower <= current_price <= upper
        note = (
            f"Final price ${current_price:,.2f} — "
            f"{'within' if in_range else 'outside'} range ${lower:,.0f}–${upper:,.0f}"
        )
        # Scenario 0 = "Yes — stays in range", Scenario 1 = "No — breaks out"
        winning = scenarios[0] if in_range else scenarios[1]
        return winning.id, note

    elif above_threshold is not None:
        above = current_price > above_threshold
        note = (
            f"Final price ${current_price:,.2f} — "
            f"{'above' if above else 'below'} threshold ${above_threshold:,.0f}"
        )
        # Scenario 0 = "Yes — above", Scenario 1 = "No — below or equal"
        winning = scenarios[0] if above else scenarios[1]
        return winning.id, note

    return None, f"Could not parse event type from title: {title}"


# ── Resolution logic (mirrors events.py router) ───────────────────────────────

def _log_probability(db: Session, scenario: Scenario, source: str = "resolved") -> None:
    db.add(ScenarioProbabilityHistory(
        scenario_id=scenario.id,
        event_id=scenario.event_id,
        probability=scenario.probability,
        source=source,
        recorded_at=datetime.utcnow(),
    ))


def _update_streak(user: User, won: bool) -> None:
    if won:
        user.current_streak = (user.current_streak or 0) + 1
        if user.current_streak > (user.best_streak or 0):
            user.best_streak = user.current_streak
    else:
        user.current_streak = 0


def _resolve_event(
    db: Session,
    event: Event,
    winning_scenario_id: int,
    resolution_note: str,
) -> dict:
    """Full resolution — identical logic to the manual resolve endpoint."""
    scenario_ids = {s.id for s in event.scenarios}
    if winning_scenario_id not in scenario_ids:
        return {"ok": False, "error": "Invalid winning_scenario_id"}

    open_predictions = (
        db.query(Prediction)
        .filter(
            Prediction.scenario_id.in_(scenario_ids),
            Prediction.status == "open",
        )
        .all()
    )

    now = datetime.utcnow()
    total_winners = total_losers = 0
    total_payout = 0.0

    for prediction in open_predictions:
        account = (
            db.query(Account)
            .filter(
                Account.user_id == prediction.user_id,
                Account.account_type == "simulation",
                Account.is_active.is_(True),
            )
            .first()
        )
        user = db.query(User).filter(User.id == prediction.user_id).first()

        if prediction.scenario_id == winning_scenario_id:
            payout = float(prediction.simulated_amount) * prediction.payout_multiplier
            pnl = payout - float(prediction.simulated_amount)
            prediction.status = "won"
            prediction.pnl = pnl
            prediction.settled_at = now
            if account:
                account.balance = float(account.balance) + payout
                db.add(Transaction(
                    user_id=prediction.user_id,
                    account_id=account.id,
                    type="prediction_win",
                    amount=payout,
                    currency=account.currency,
                ))
            if user:
                _update_streak(user, won=True)
            total_winners += 1
            total_payout += payout
        else:
            prediction.status = "lost"
            prediction.pnl = -float(prediction.simulated_amount)
            prediction.settled_at = now
            if account:
                db.add(Transaction(
                    user_id=prediction.user_id,
                    account_id=account.id,
                    type="prediction_loss",
                    amount=0,
                    currency=account.currency,
                ))
            if user:
                _update_streak(user, won=False)
            total_losers += 1

    # Update event + scenarios
    event.status = "resolved"
    event.resolution_note = resolution_note
    event.resolved_at = now

    for scenario in event.scenarios:
        scenario.status = "won" if scenario.id == winning_scenario_id else "lost"
        scenario.probability = 100.0 if scenario.id == winning_scenario_id else 0.0
        _log_probability(db, scenario, source="auto_resolved")

    db.commit()

    return {
        "ok": True,
        "event_id": event.id,
        "winning_scenario_id": winning_scenario_id,
        "total_winners": total_winners,
        "total_losers": total_losers,
        "total_payout": round(total_payout, 2),
        "resolution_note": resolution_note,
    }


# ── Main resolver loop ────────────────────────────────────────────────────────

async def run_auto_resolver() -> None:
    """
    Check for expired crypto events and auto-resolve them.
    Called every 60 seconds from the scheduler.
    """
    now = datetime.utcnow()
    db: Session = SessionLocal()

    try:
        # Find open crypto events that have passed their closing time
        expired_events = (
            db.query(Event)
            .options(joinedload(Event.scenarios))
            .filter(
                Event.status == "open",
                Event.category == "crypto",
                Event.closes_at != None,
                Event.closes_at <= now,
            )
            .all()
        )

        if not expired_events:
            return

        logger.info(f"[AutoResolver] Found {len(expired_events)} expired events to resolve.")

        # Fetch current prices once for all events
        try:
            prices = await fetch_current_prices()
        except Exception as e:
            logger.error(f"[AutoResolver] Failed to fetch prices: {e}")
            return

        resolved_count = 0
        skipped_count = 0

        for event in expired_events:
            coin = _detect_coin(event.title)
            if not coin:
                logger.warning(f"[AutoResolver] Could not detect coin for event #{event.id}: {event.title}")
                skipped_count += 1
                continue

            current_price = prices.get(coin)
            if current_price is None:
                logger.warning(f"[AutoResolver] No price available for {coin}, skipping event #{event.id}")
                skipped_count += 1
                continue

            winning_id, note = _determine_winner(event, current_price)
            if winning_id is None:
                logger.warning(f"[AutoResolver] Could not determine winner for event #{event.id}: {note}")
                skipped_count += 1
                continue

            result = _resolve_event(db, event, winning_id, note)

            if result["ok"]:
                logger.info(
                    f"[AutoResolver] ✓ Resolved event #{event.id} '{event.title[:50]}' | "
                    f"{coin} @ ${current_price:,.2f} | "
                    f"Winners: {result['total_winners']} · Losers: {result['total_losers']} · "
                    f"Payout: ${result['total_payout']:,.2f} | {note}"
                )
                resolved_count += 1
            else:
                logger.error(f"[AutoResolver] ✗ Failed event #{event.id}: {result.get('error')}")
                skipped_count += 1

        if resolved_count > 0 or skipped_count > 0:
            logger.info(f"[AutoResolver] Done — resolved: {resolved_count}, skipped: {skipped_count}")

    except Exception as e:
        logger.error(f"[AutoResolver] Unexpected error: {e}")
        db.rollback()
    finally:
        db.close()


async def start_auto_resolver() -> None:
    """Runs the auto-resolver every 60 seconds."""
    logger.info("[AutoResolver] Started — checking every 60 seconds.")
    while True:
        await run_auto_resolver()
        await asyncio.sleep(CHECK_INTERVAL_SECONDS)