"""
app/services/auto_resolver.py

Automatically resolves expired crypto prediction events.

Runs every 60 seconds. For each open crypto event past its closes_at:
1. Fetches the current price from CoinGecko
2. Parses the event title to extract the coin + threshold/range
3. Determines the winning scenario (Yes or No)
4. Runs the full resolution logic (payouts, streaks, snapshots)

Supported event types (generated by event_generator.py):
  - "Will BTC be above $70,000 in 1 hour?"   → above/below threshold
  - "Will ETH stay between $2,100–$2,196...?" → price range check
"""

from __future__ import annotations

import asyncio
import logging
import re
from datetime import datetime

import httpx
from sqlalchemy.orm import Session, joinedload

from app.db import SessionLocal
from app.models.event import Event
from app.models.scenario import Scenario
from app.services.resolution import settle_event, void_event

logger = logging.getLogger(__name__)

COINGECKO_URL = "https://api.coingecko.com/api/v3/simple/price"

COIN_KEYWORDS = {
    "BTC": "bitcoin",
    "ETH": "ethereum",
    "SOL": "solana",
    "BNB": "binancecoin",
}

CURRENCY = "usd"
CHECK_INTERVAL_SECONDS = 300  # run every 5 minutes instead of every 60s

# Simple in-memory price cache — avoids hammering CoinGecko
_price_cache: dict[str, float] = {}
_price_cache_time: float = 0
PRICE_CACHE_TTL = 120  # reuse prices for 2 minutes


# ── Price fetching ────────────────────────────────────────────────────────────

async def fetch_current_prices() -> dict[str, float]:
    """Fetch live prices for all tracked coins, with caching."""
    import time
    global _price_cache, _price_cache_time

    now = time.time()
    if _price_cache and (now - _price_cache_time) < PRICE_CACHE_TTL:
        return _price_cache

    params = {"ids": ",".join(COIN_KEYWORDS.values()), "vs_currencies": CURRENCY}
    async with httpx.AsyncClient(timeout=10) as client:
        response = await client.get(COINGECKO_URL, params=params)
        response.raise_for_status()
        data = response.json()

    # Invert to symbol → price
    import time
    id_to_symbol = {v: k for k, v in COIN_KEYWORDS.items()}
    prices = {
        id_to_symbol[coin_id]: float(data[coin_id][CURRENCY])
        for coin_id in COIN_KEYWORDS.values()
        if coin_id in data and CURRENCY in data[coin_id]
    }
    _price_cache = prices
    _price_cache_time = time.time()
    return prices


# ── Event parsing ─────────────────────────────────────────────────────────────

def _detect_coin(title: str) -> str | None:
    """Detect which coin this event is about from the title."""
    t = title.upper()
    for symbol in COIN_KEYWORDS:
        if symbol in t:
            return symbol
    return None


def _parse_above_event(title: str) -> float | None:
    """
    Parse threshold from: "Will BTC be above $70,000 in 1 hour?"
    Returns the threshold price or None if can't parse.
    """
    match = re.search(r"above\s+\$([0-9,]+(?:\.[0-9]+)?)", title, re.IGNORECASE)
    if match:
        return float(match.group(1).replace(",", ""))
    return None


def _parse_range_event(title: str) -> tuple[float, float] | None:
    """
    Parse range from: "Will BTC stay between $68,820–$71,628 in 1 hour?"
    Returns (lower, upper) or None if can't parse.
    """
    match = re.search(
        r"between\s+\$([0-9,]+(?:\.[0-9]+)?)[–\-–]?\$?([0-9,]+(?:\.[0-9]+)?)",
        title, re.IGNORECASE
    )
    if match:
        lower = float(match.group(1).replace(",", ""))
        upper = float(match.group(2).replace(",", ""))
        return lower, upper
    return None


def _determine_winner(event: Event, current_price: float) -> tuple[int | None, str]:
    """
    Determine winning scenario ID and resolution note.
    Returns (winning_scenario_id, resolution_note) or (None, reason) if undetermined.
    """
    title = event.title
    scenarios = sorted(event.scenarios, key=lambda s: s.sort_order)

    if not scenarios:
        return None, "No scenarios found"

    # Detect event type
    range_result = _parse_range_event(title)
    above_threshold = _parse_above_event(title)

    if range_result:
        lower, upper = range_result
        in_range = lower <= current_price <= upper
        note = (
            f"Final price ${current_price:,.2f} — "
            f"{'within' if in_range else 'outside'} range ${lower:,.0f}–${upper:,.0f}"
        )
        # Scenario 0 = "Yes — stays in range", Scenario 1 = "No — breaks out"
        winning = scenarios[0] if in_range else scenarios[1]
        return winning.id, note

    elif above_threshold is not None:
        above = current_price > above_threshold
        note = (
            f"Final price ${current_price:,.2f} — "
            f"{'above' if above else 'below'} threshold ${above_threshold:,.0f}"
        )
        # Scenario 0 = "Yes — above", Scenario 1 = "No — below or equal"
        winning = scenarios[0] if above else scenarios[1]
        return winning.id, note

    return None, f"Could not parse event type from title: {title}"


# ── Main resolver loop ────────────────────────────────────────────────────────

async def run_auto_resolver() -> None:
    """
    Check for expired crypto events and auto-resolve them.
    Called every 60 seconds from the scheduler.
    """
    now = datetime.utcnow()
    db: Session = SessionLocal()

    try:
        # Find open crypto events that have passed their closing time
        expired_events = (
            db.query(Event)
            .options(joinedload(Event.scenarios))
            .filter(
                Event.status == "open",
                Event.category == "crypto",
                Event.closes_at != None,
                Event.closes_at <= now,
            )
            .all()
        )

        if not expired_events:
            return

        logger.info(f"[AutoResolver] Found {len(expired_events)} expired events to resolve.")

        # Fetch current prices once for all events
        try:
            prices = await fetch_current_prices()
        except Exception as e:
            logger.error(f"[AutoResolver] Failed to fetch prices: {e}")
            return

        resolved_count = 0
        skipped_count = 0

        for event in expired_events:
            coin = _detect_coin(event.title)
            if not coin:
                logger.warning(f"[AutoResolver] Could not detect coin for event #{event.id}: {event.title}")
                skipped_count += 1
                continue

            current_price = prices.get(coin)
            if current_price is None:
                logger.warning(f"[AutoResolver] No price available for {coin}, skipping event #{event.id}")
                skipped_count += 1
                continue

            winning_id, note = _determine_winner(event, current_price)
            if winning_id is None:
                logger.warning(f"[AutoResolver] Could not determine winner for event #{event.id}: {note}")
                skipped_count += 1
                continue

            result = settle_event(db, event, winning_id, note)

            if result["ok"]:
                logger.info(
                    f"[AutoResolver] ✓ Resolved event #{event.id} '{event.title[:50]}' | "
                    f"{coin} @ ${current_price:,.2f} | "
                    f"Winners: {result['total_winners']} · Losers: {result['total_losers']} · "
                    f"Payout: ${result['total_payout']:,.2f} | {note}"
                )
                resolved_count += 1
            else:
                logger.error(f"[AutoResolver] ✗ Failed event #{event.id}: {result.get('error')}")
                skipped_count += 1

        if resolved_count > 0 or skipped_count > 0:
            logger.info(f"[AutoResolver] Done — resolved: {resolved_count}, skipped: {skipped_count}")

        # Void expired non-crypto events (48-hour grace period after closes_at)
        from datetime import timedelta
        grace_cutoff = now - timedelta(hours=48)
        expired_noncrypto = (
            db.query(Event)
            .options(joinedload(Event.scenarios))
            .filter(
                Event.status == "open",
                Event.category != "crypto",
                Event.closes_at != None,
                Event.closes_at <= grace_cutoff,
            )
            .all()
        )
        for event in expired_noncrypto:
            result = void_event(db, event, note="Event expired after 48-hour grace period — all bets refunded")
            logger.info(f"[AutoResolver] Voided expired event #{event.id} '{event.title[:50]}' — refunded {result['refunded']} bets")

    except Exception as e:
        logger.error(f"[AutoResolver] Unexpected error: {e}")
        db.rollback()
    finally:
        db.close()


async def start_auto_resolver() -> None:
    """Runs the auto-resolver every 60 seconds."""
    logger.info("[AutoResolver] Started — checking every 60 seconds.")
    while True:
        await run_auto_resolver()
        await asyncio.sleep(CHECK_INTERVAL_SECONDS)